import type { GroundStation } from '@/domain/types';

export const defaultGroundStations: GroundStation[] = [
  {
    id: 'gs-nasa-asf-fairbanks',
    name: 'NASA ASF Fairbanks',
    latDeg: 64.794,
    lonDeg: -147.536,
    altitudeM: 180,
    elevationMaskDeg: 8,
    enabled: true,
    schemaVersion: 1,
  },
  {
    id: 'gs-ksat-svalbard',
    name: 'KSAT Svalbard',
    latDeg: 78.23,
    lonDeg: 15.39,
    altitudeM: 480,
    elevationMaskDeg: 5,
    enabled: true,
    schemaVersion: 1,
  },
  {
    id: 'gs-ssc-kiruna',
    name: 'SSC Kiruna / Esrange',
    latDeg: 67.8833,
    lonDeg: 21.0667,
    altitudeM: 341,
    elevationMaskDeg: 5,
    enabled: true,
    schemaVersion: 1,
  },
  {
    id: 'gs-ssc-santiago',
    name: 'SSC Santiago',
    latDeg: -33.15,
    lonDeg: -70.66,
    altitudeM: 723,
    elevationMaskDeg: 8,
    enabled: true,
    schemaVersion: 1,
  },
  {
    id: 'gs-ksat-trollsat',
    name: 'KSAT TrollSat',
    latDeg: -72.0167,
    lonDeg: 2.5333,
    altitudeM: 1365,
    elevationMaskDeg: 5,
    enabled: true,
    schemaVersion: 1,
  },
  {
    id: 'gs-nasa-wallops',
    name: 'NASA Wallops',
    latDeg: 37.94,
    lonDeg: -75.47,
    altitudeM: 3,
    elevationMaskDeg: 10,
    enabled: true,
    schemaVersion: 1,
  },
  {
    id: 'gs-nasa-white-sands',
    name: 'NASA White Sands',
    latDeg: 32.5,
    lonDeg: -106.61,
    altitudeM: 1210,
    elevationMaskDeg: 10,
    enabled: true,
    schemaVersion: 1,
  },
  {
    id: 'gs-nasa-mcmurdo',
    name: 'NASA McMurdo',
    latDeg: -77.85,
    lonDeg: 166.67,
    altitudeM: 20,
    elevationMaskDeg: 5,
    enabled: true,
    schemaVersion: 1,
  },
  {
    id: 'gs-dsn-goldstone',
    name: 'DSN Goldstone',
    latDeg: 35.4267,
    lonDeg: -116.89,
    altitudeM: 1000,
    elevationMaskDeg: 10,
    enabled: true,
    schemaVersion: 1,
  },
  {
    id: 'gs-dsn-madrid',
    name: 'DSN Madrid',
    latDeg: 40.43,
    lonDeg: -4.25,
    altitudeM: 850,
    elevationMaskDeg: 10,
    enabled: true,
    schemaVersion: 1,
  },
  {
    id: 'gs-dsn-canberra',
    name: 'DSN Canberra',
    latDeg: -35.4,
    lonDeg: 148.98,
    altitudeM: 690,
    elevationMaskDeg: 10,
    enabled: true,
    schemaVersion: 1,
  },
  {
    id: 'gs-sansa-hartebeesthoek',
    name: 'SANSA Hartebeesthoek',
    latDeg: -25.89,
    lonDeg: 27.69,
    altitudeM: 1415,
    elevationMaskDeg: 8,
    enabled: true,
    schemaVersion: 1,
  },
  {
    id: 'gs-seoul',
    name: 'Seoul Ops',
    latDeg: 37.5665,
    lonDeg: 126.978,
    altitudeM: 38,
    elevationMaskDeg: 10,
    enabled: true,
    schemaVersion: 1,
  },
  {
    id: 'gs-houston',
    name: 'Houston Backup',
    latDeg: 29.7604,
    lonDeg: -95.3698,
    altitudeM: 13,
    elevationMaskDeg: 12,
    enabled: true,
    schemaVersion: 1,
  },
];
